project:
  type: book

book:
  title: "Taller de programación R - SERNANP"
  author: "Roy Yali"
  favicon: https://geoportal.sernanp.gob.pe/wp-content/uploads/2019/12/logo_sernanp-01.png
  description: Taller de programación en el lenguaje de programación R para servidores de SERNANP.
  keyword: polars, pandas, python, dataframe, performance, data science, data engineering
  url: https://ryali93.github.io/rsernanp/
  navbar: 
    logo: https://geoportal.sernanp.gob.pe/wp-content/uploads/2019/12/logo_sernanp-01.png
    background: "#738347"
    right: 
      - header_right.qmd
  sidebar: 
    background: "#FCCF80"
    logo: fig/oso.png
    search: true
  repo-url: https://github.com/ryali93/rsernanp/
  repo-subdir: book
  repo-branch: master
  repo-actions: [edit, issue, source]
  sharing: [twitter, facebook, linkedin]
  image: polar-bear-airpods-no-background.png
  open-graph:
    image: https://geoportal.sernanp.gob.pe/wp-content/uploads/2019/12/logo_sernanp-01.png
    description: A side-by-side comparison of the Polars and Pandas libraries.
      
  page-footer:
    left: "Copyright (c) | Powered by [Quarto](https://quarto.org/) <?quarto.version?>"
    background: "#738347"

  chapters:
    - index.qmd
    - c01_introduccion.qmd
    - c02_intro_R.qmd
    - c03_intro_R2.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true

editor: visual
